[package]
name = "core-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror.workspace = true
tracing = { workspace = true }
headless_chrome = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"
hex = "0.4"
uuid = { version = "1.0", features = ["v4"] }
json-patch = "4.1"
crossbeam-channel = "0.5"
regex = "1.12.3"
url = "2.5"

[dev-dependencies]
urlencoding = "2.1"
image = { version = "0.25", default-features = false, features = ["png"] }
jsonschema = "0.37"
